export const Colors = {
  jake: {
    tabIconDefault: '#ffffd4',
    tabIconSelected: '#e7e1b2',
    card: '#31251f',
    border: 'orange',
    primary: 'red',
    background: '#f6bb12',
    text: '#31251f',
    notification: 'brown',
    tint: 'gray',
    icon: 'black',
    activeButton: 'yellow',
    playButton: '#ffffd4',
    fontColor: '#31251f',
    keyboard: {
      defaultKeyColor: 'white',
      correctPositionColor: '#77ca4a',
      wrongPositionColor: '#ca4a77',
      activeKeyColor: '#cccccc',
      winningColor: 'black'
    },
    gameboard: {
      border: '#333',
      background: '#f0f0f0',
      text: '#000',
    },
  },
  finn: {
    tabIconDefault: '#05aed5',
    tabIconSelected: 'white',
    card: '#0162cd',
    border: 'darkblue',
    primary: 'skyblue',
    background: 'white',
    text: 'darkblue',
    notification: 'blue',
    tint: 'gray',
    icon: 'navy',
    activeButton: 'lightblue',
    playButton: '#e0f7fa',
    fontColor: '#0d47a1',
    keyboard: {
      defaultKeyColor: '#e0f7fa',
      correctPositionColor: '#b4ff8d',
      wrongPositionColor: '#f4d85b',
      activeKeyColor: '#cccccc',
      winningColor: 'black'
    },
    gameboard: {
      border: '#aaa',
      background: '#fff',
      text: '#333',
    },
  },
  bmo: {
    tabIconDefault: 'green',
    tabIconSelected: 'lightgreen',
    card: 'teal',
    border: 'darkgreen',
    primary: 'lime',
    background: 'cyan',
    text: 'black',
    notification: 'lime',
    tint: 'gray',
    icon: 'darkgreen',
    activeButton: 'teal',
    playButton: '#b2dfdb',
    fontColor: '#004d40',
    keyboard: {
      defaultKeyColor: 'brown',
      correctPositionColor: 'black',
      wrongPositionColor: 'yellow',
      activeKeyColor: '#cccccc',
      winningColor: 'black'
    },
    gameboard: {
      border: '#555',
      background: '#dfe6e9',
      text: '#2d3436',
    },
  },
};
