export const Colors = {
  jake: {
    tabIconDefault: '#ffffd4',
    tabIconSelected: '#e7e1b2',
    card: '#31251f',
    border: 'orange',
    primary: 'red',
    background: '#f6bb12',
    text: '#31251f',
    notification: 'brown',
    tint: 'gray',
    icon: 'black',
    activeButton: 'yellow',
    playButton: '#ffffd4',
    playButtonText: 'black',
    fontColor: '#31251f',
    keyboard: {
      defaultKeyColor: 'white',
      correctPositionColor: '#77ca4a',
      wrongPositionColor: '#ca4a77',
      activeKeyColor: '#cccccc',
      winningColor: '#05aed5'
    },
    gameboard: {
      border: '#333',
      background: '#f0f0f0',
      text: '#000',
    },
  },
  finn: {
    tabIconDefault: '#05aed5',
    tabIconSelected: 'white',
    card: '#0162cd',
    border: 'darkblue',
    primary: 'skyblue',
    background: 'white',
    text: 'darkblue',
    notification: 'blue',
    tint: 'gray',
    icon: 'navy',
    activeButton: 'lightblue',
    playButton: '#e0f7fa',
    playButtonText: 'darkblue',
    newGameButton: '#e0f7fa',
    newGameButtonText: 'darkblue',
    fontColor: '#0d47a1',
    keyboard: {
      defaultKeyColor: '#e0f7fa',
      correctPositionColor: '#b4ff8d',
      wrongPositionColor: '#f4d85b',
      activeKeyColor: '#cccccc',
      winningColor: '#05aed5'
    },
    gameboard: {
      border: '#aaa',
      background: '#fff',
      text: '#333',
    },
  },
  bmo: {
    tabIconDefault: '#d9ffea',
    tabIconSelected: '#ffec47',
    card: '#62afb7',
    border: 'darkgreen',
    primary: 'lime',
    background: '#d9ffea',
    text: '#0a1d20',
    notification: 'lime',
    tint: 'gray',
    icon: 'darkgreen',
    activeButton: 'teal',
    playButton: '#63bda4',
    playButtonText: '#f20553',
    fontColor: '#004d40',
    keyboard: {
      defaultKeyColor: '#63bda4',
      correctPositionColor: '#549454',
      wrongPositionColor: '#f20553',
      activeKeyColor: '#d4d4dc',
      winningColor: '#44b097'
    },
    gameboard: {
      border: '#555',
      background: '#dfe6e9',
      text: '#2d3436',
    },
  },
};
